### ISSUE TITLE
Logo for ARIA-P

### ISSUE THREAD

**Issue by lewismc** [aria-p/aria-p.github.io#3]
We should design a logo for the project. It is always nice to have something to push onto the website.

**Comment by andychase** [comment]
I agree. Since we are a bit early on the project it's a little hard to design some of the marketing aspects, but we can always update stuff later in the project.

What I usually do for logos is combine a few icons from [Font Awesome](https://fortawesome.github.io/Font-Awesome/). I can look into making a few quick ones and suggest them on the list.

**Comment by andychase** [comment]
These were posted to the mailing list awhile back
